package core

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// VaultConfig is the committed, per-vault contract stored at
// <vault>/.hebb/config.toml. It self-identifies a vault and configures the
// parts of hebb that vary per vault (excludes, web port, enabled jobs).
// Skills are not configured here: install delivers the full bundle to the
// user-global skills dirs, shared across vaults.
type VaultConfig struct {
	Name        string       `toml:"name"`
	ExcludeDirs []string     `toml:"exclude_dirs"`
	WebPort     int          `toml:"web_port"`
	Jobs        []string     `toml:"jobs"`
	JobArgs     JobArgs      `toml:"job_args"`
	Git         GitConfig    `toml:"git"`
	Update      UpdateConfig `toml:"update"`
}

// JobArgs is the committed [job_args] block: extra command-line arguments
// appended to a job's rendered launchd program, keyed by job name. Entries for
// job names not listed under jobs (or unknown to hebb) are ignored, e.g.
//
//	[job_args]
//	action-review = ["--owner", "Alex Doe"]
type JobArgs map[string][]string

// UpdateConfig is the committed [update] block. The scheduled update-check job
// reports a newer release by default; with auto = true it installs it (opt-in,
// since self-replacing a binary unattended is a deliberate choice).
type UpdateConfig struct {
	Auto bool `toml:"auto"`
}

// GitConfig is the committed [git] block. Git mode keeps the vault's markdown in
// sync with a remote (pull before work, commit + push after). It is off unless
// enabled is true. AutoPull/AutoPush are pointers so an unset value defaults to
// on (only meaningful when enabled), while an explicit false turns that half
// off.
type GitConfig struct {
	Enabled         bool   `toml:"enabled"`
	AutoPull        *bool  `toml:"auto_pull"`        // default true when enabled
	AutoPush        *bool  `toml:"auto_push"`        // default true when enabled
	DebounceSeconds int    `toml:"debounce_seconds"` // watcher quiet-period before a sync; default 10
	CommitMessage   string `toml:"commit_message"`   // default "hebb: sync vault"
}

const defaultGitDebounceSeconds = 10

// PullEnabled reports whether git mode should pull (on by default when enabled).
func (g GitConfig) PullEnabled() bool {
	return g.Enabled && (g.AutoPull == nil || *g.AutoPull)
}

// PushEnabled reports whether git mode should commit+push (on by default when enabled).
func (g GitConfig) PushEnabled() bool {
	return g.Enabled && (g.AutoPush == nil || *g.AutoPush)
}

// Debounce is the resolved quiet-period in seconds before the watcher syncs.
func (g GitConfig) Debounce() int {
	if g.DebounceSeconds > 0 {
		return g.DebounceSeconds
	}
	return defaultGitDebounceSeconds
}

// Message is the resolved auto-commit message.
func (g GitConfig) Message() string {
	if g.CommitMessage != "" {
		return g.CommitMessage
	}
	return defaultCommitMessage
}

// DefaultVaultConfig returns the baseline config for a vault of the given name.
func DefaultVaultConfig(name string) VaultConfig {
	return VaultConfig{
		Name:        name,
		ExcludeDirs: append([]string(nil), defaultExcludeDirs...),
		WebPort:     defaultWebPort,
		Jobs:        []string{"daily-digest", "action-review", "web", "update-check"},
	}
}

const defaultWebPort = 4321

// vaultConfigPath is the canonical location of the committed config file.
func vaultConfigPath(vaultPath string) string {
	return filepath.Join(vaultPath, ".hebb", "config.toml")
}

// LoadVaultConfig reads <vault>/.hebb/config.toml. The boolean reports whether
// the file existed: when it does not, defaults named after the vault directory
// are returned so callers always receive a usable config. A malformed file is
// an error.
func LoadVaultConfig(vaultPath string) (VaultConfig, bool, error) {
	path := vaultConfigPath(vaultPath)
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return DefaultVaultConfig(filepath.Base(vaultPath)), false, nil
	}
	if err != nil {
		return VaultConfig{}, false, err
	}
	var vc VaultConfig
	if err := toml.Unmarshal(data, &vc); err != nil {
		return VaultConfig{}, false, fmt.Errorf("parse %s: %w", path, err)
	}
	return vc, true, nil
}

// Save writes the config to <vault>/.hebb/config.toml, creating .hebb/ if
// needed. It is idempotent.
func (vc VaultConfig) Save(vaultPath string) error {
	path := vaultConfigPath(vaultPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("# hebb vault config - committed; identifies and configures this vault.\n")
	buf.WriteString("# Generated by 'hebb install'. Safe to edit.\n\n")
	if err := toml.NewEncoder(&buf).Encode(vc); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}
