package core

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// VaultConfig is the committed, per-vault contract stored at
// <vault>/.hebb/config.toml. It self-identifies a vault and configures the
// parts of hebb that vary per vault (excludes, web port, enabled jobs/skills).
type VaultConfig struct {
	Name        string   `toml:"name"`
	ExcludeDirs []string `toml:"exclude_dirs"`
	WebPort     int      `toml:"web_port"`
	Jobs        []string `toml:"jobs"`
	Skills      []string `toml:"skills"`
}

// DefaultVaultConfig returns the baseline config for a vault of the given name.
func DefaultVaultConfig(name string) VaultConfig {
	return VaultConfig{
		Name:        name,
		ExcludeDirs: append([]string(nil), defaultExcludeDirs...),
		WebPort:     defaultWebPort,
		Jobs:        []string{"daily-digest", "action-review", "web"},
		Skills:      []string{"vault-ingest"},
	}
}

const defaultWebPort = 4321

// vaultConfigPath is the canonical location of the committed config file.
func vaultConfigPath(vaultPath string) string {
	return filepath.Join(vaultPath, ".hebb", "config.toml")
}

// LoadVaultConfig reads <vault>/.hebb/config.toml. The boolean reports whether
// the file existed: when it does not, defaults named after the vault directory
// are returned so callers always receive a usable config. A malformed file is
// an error.
func LoadVaultConfig(vaultPath string) (VaultConfig, bool, error) {
	path := vaultConfigPath(vaultPath)
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return DefaultVaultConfig(filepath.Base(vaultPath)), false, nil
	}
	if err != nil {
		return VaultConfig{}, false, err
	}
	var vc VaultConfig
	if err := toml.Unmarshal(data, &vc); err != nil {
		return VaultConfig{}, false, fmt.Errorf("parse %s: %w", path, err)
	}
	return vc, true, nil
}

// Save writes the config to <vault>/.hebb/config.toml, creating .hebb/ if
// needed. It is idempotent.
func (vc VaultConfig) Save(vaultPath string) error {
	path := vaultConfigPath(vaultPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("# hebb vault config - committed; identifies and configures this vault.\n")
	buf.WriteString("# Generated by 'hebb install'. Safe to edit.\n\n")
	if err := toml.NewEncoder(&buf).Encode(vc); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}
