package install

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// A vault is self-contained (committed notes, config, memory) but does not carry
// the hebb binary. WriteBootstrap drops a committed bootstrap.sh at the vault
// root so a fresh clone or an ephemeral runner can self-provision: the script
// installs the hebb binary from GitHub if absent, then wires the vault with
// `hebb install`. This is the "clone-and-go / from-scratch always works" guarantee.

// RenderBootstrap returns the bootstrap.sh contents. By default it pins the hebb
// version when version is a clean release (so a clone gets a binary new enough
// to open the vault's index); a dev or unknown version leaves the pin off so
// install.sh fetches the latest release. When trackLatest is true it pins to
// "latest" so a clone always installs the newest release (config [bootstrap]
// track_latest).
func RenderBootstrap(version string, trackLatest bool) []byte {
	pin := releasePin(version)
	if trackLatest {
		pin = "latest"
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# hebb vault bootstrap - committed; makes this vault self-installing.\n")
	b.WriteString("# Generated by hebb. On a fresh clone or an ephemeral machine, run\n")
	b.WriteString("# ./bootstrap.sh: it installs the hebb binary from GitHub if absent,\n")
	b.WriteString("# then wires this vault (hebb install). Idempotent; safe to re-run.\n")
	b.WriteString("# Re-auth any connectors afterwards (the one manual step).\n")
	b.WriteString("set -eu\n\n")
	if pin != "" {
		fmt.Fprintf(&b, "HEBB_VERSION=\"${HEBB_VERSION:-%s}\"; export HEBB_VERSION\n", pin)
	}
	b.WriteString("VAULT=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n\n")
	b.WriteString("if ! command -v hebb >/dev/null 2>&1; then\n")
	b.WriteString("\tcurl -fsSL https://raw.githubusercontent.com/cizer/hebb/main/install.sh | sh\n")
	b.WriteString("fi\n")
	b.WriteString("export PATH=\"$HOME/.local/bin:$PATH\"\n\n")
	b.WriteString("exec hebb install --vault \"$VAULT\" --no-interaction\n")
	return []byte(b.String())
}

// WriteBootstrap writes bootstrap.sh (executable) at the vault root. Idempotent:
// it rewrites only when the contents differ, so the version pin tracks the hebb
// that last installed the vault. Returns true if the file was created or changed.
func WriteBootstrap(vaultPath, version string, trackLatest bool) (bool, error) {
	path := filepath.Join(vaultPath, "bootstrap.sh")
	want := RenderBootstrap(version, trackLatest)
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, want) {
		return false, nil
	}
	if err := os.WriteFile(path, want, 0o755); err != nil {
		return false, err
	}
	return true, nil
}

// releasePin returns version when it is a clean release tag (vX.Y.Z), else "".
// A dev build ("0.0.0-dev (rev)") or any unparseable version yields "", so the
// bootstrap omits the pin and install.sh resolves the latest release.
func releasePin(version string) string {
	if strings.Contains(strings.ToLower(version), "dev") {
		return ""
	}
	if _, _, _, ok := ParseVersion(version); !ok {
		return ""
	}
	return strings.TrimSpace(version)
}
